version: '3.7'

services:
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      # PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 80:80
    volumes:
      - /sessions

  mysql:
    image: mysql:8
    container_name: database-mysql8
    restart: always
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
      - SYS_PTRACE
      - SYS_RESOURCE
    command: [
        # --innodb-dedicated-server=ON,
        --default-authentication-plugin=mysql_native_password
        ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: posjr
      MYSQL_USER: posjr
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      # - mysql_data:/var/lib/mysql
      - ./mysql_data:/var/lib/mysql
    # logging:
    #   driver: 'json-file'
    #   options:
    #     max-size: '8m'
    #     max-file: '3'
    deploy:
      resources:
        limits:
          #cpus: '0.92'
          memory: 512M
        # reservations:
          #cpus: '0.5'
          # memory: 768M

# volumes:
#   mysql8_data:
